### ISSUE TITLE
Better error messages when fetching a buildpack fails

### ISSUE THREAD

**Issue by msakrejda** [ddollar/heroku-buildpack-multi#24]
If a buildpack URL is specified incorrectly (or if the fetch dies for another reason), the error message is pretty generic:

```
Fetching repository, done.
Counting objects: 43, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (25/25), done.
Writing objects: 100% (25/25), 3.86 KiB | 0 bytes/s, done.
Total 25 (delta 17), reused 0 (delta 0)

-----> Deleting 4 files matching .slugignore patterns.
-----> Fetching custom git buildpack... done
-----> Multipack app detected
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-toolbelt.git

! Push rejected, failed to compile Multipack app
```

Would something like

``` bash
git clone $url $dir >/dev/null 2>&1 || { echo "Could not download buildpack"; exit 1 }
```

make sense? Ideally, we'd get distinguish a 404 from other errors, too, but this could help.

**Comment by rreusser** [comment]
It looks like pull request #25 was not merged due to excessive visual pollution. I'm stuck though trying to use `browserify-rails`. [As per instructions](https://github.com/browserify-rails/browserify-rails#deploying-to-heroku), I've added a the `heroku-buildpack-multi` buildpack and a `.buildpacks` file:

```
# .buildpacks
https://github.com/heroku/heroku-buildpack-nodejs.git
https://github.com/heroku/heroku-buildpack-ruby.git
```

I have a Gemfile and package.json with what appear to be the required fields (based on a bit of googling. Can paste if interested, but it's not strictly the point.) I just get:

```
Counting objects: 75, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (70/70), done.
Writing objects: 100% (75/75), 9.86 KiB | 0 bytes/s, done.
Total 75 (delta 45), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Removing .DS_Store files
remote: -----> Fetching custom git buildpack... done
remote: -----> Multipack app detected
remote: =====> Downloading Buildpack: .buildpacks
remote: 
remote:  !     Push rejected, failed to compile Multipack app
remote: 
remote: Verifying deploy...
remote: 
remote: !	Push rejected to app-name.
remote: 
To https://git.heroku.com/app-name.git
 ! [remote rejected] stage -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/app-name.git'
```

From what I can tell and without an understanding of buildpack internals, this basically gives me nothing to go on. Please correct me if I'm missing something. Perhaps I need specific commit hashes in my .buildpacks as the README suggests? It's just guesswork. Is there any way to move forward?

**Comment by uhoh-itsmaciek** [comment]
@rreusser Heroku now [supports multiple buildpacks natively](https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app)--maybe try that instead?

**Comment by rreusser** [comment]
Culprit: my unfamiliarity with buildpacks. Figured if nothing else, this'll be an easy google hit for someone else with the same issue. [PR submitted](https://github.com/browserify-rails/browserify-rails/pull/95) for browserify-rails docs and issue solved. Thanks again for the prompt reply!
